import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  alert("Situs tidak aman! \nSitus ini hanya dipergunakan semata-mata sebagai sarana edukasi mengenai serangan siber yang berbentuk phising. \nAnda tidak perlu mempercayai setiap informasi yang ada pada situs ini. \nSitus ini juga mencoba meniru tampilan situs login milik google. \nSegala elemen yang ada pada tampilan login situs ini tidak lain milik google")
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
